export const DATA_FETCHED_START = 'DATA_FETCHED_START';
export const DATA_FETCHED_SUCCESSFULLY = 'DATA_FETCHED_SUCCESSFULLY';
export const DATA_FETCHED_FAILURE = 'DATA_FETCHED_FAILURE';
export const DATA_UPDATED_START = 'DATA_UPDATED_START';
export const DATA_UPDATED_SUCCESSFULLY = 'DATA_UPDATED_SUCCESSFULLY';
export const DATA_UPDATED_FAILURE = 'DATA_UPDATED_FAILURE';
export const DATA_DELETED_START = 'DATA_DELETED_START';
export const DATA_DELETED_SUCCESSFULLY = 'DATA_DELETED_SUCCESSFULLY';
export const DATA_DELETED_FAILURE = 'DATA_DELETED_FAILURE';
export const DATA_ADDED_START = 'DATA_ADDED_START';
export const DATA_ADDED_SUCCESSFULLY = 'DATA_ADDED_SUCCESSFULLY';
export const DATA_ADDED_FAILURE = 'DATA_ADDED_FAILURE';

